### PR TITLE
Updated to Py3 code style, removed Six and mock dependencies

### PR DESCRIPTION
**Pull request by smithdc1**

### CODE REVIEW

**Comment by smithdc1** [comment]
Python 3.5 is failing. What's the view on keeping 3.5 support for this package given it has reached end-of-life?

**Comment by frennkie** [comment]
In general I like that we are cleaning up here. But regarding Python3.5 I am a bit reluctant to remove the compatibility now.

Both Ubuntu 16.04 and Debian 9 default to Py35 and are still fully supported. I would suggest to hold of for a few more month. 

@dokterbob What is your view on this?

**Comment by smithdc1** [comment]
I've currently skipped the failing test on 3.5. This is due to `assert_called_once()` being added in Python3.6. Not sure if adding back the Mock dependency in its entirety is worth it for this one test?

**Comment by frennkie** [comment]
> Not sure if adding back the Mock dependency in its entirety is worth it for this one test?

I would say: No - not worth it.

Otherwise this looks good to me.

**Pull request merged**
